#!/bin/sh
# Wrapper for openssl, to ensure a validation result is recorded
OPENSSL=$1
shift
OUTPUT=`$OPENSSL $*`
RESULT=$?
echo "$OUTPUT"
SEENERR=`echo "$OUTPUT" | grep error`
if [ "$SEENERR" != "" ]; then
    RESULT=123
fi
if [ $RESULT -ne 0 ]; then
    echo "TLS-VALIDATION: Failed"
else
    echo "TLS-VALIDATION: Success"
fi

