#!/usr/bin/env python
import sys
import base64

def pem2der(infile):
    lines = infile.readlines()
    incert = False
    pem = ""
    for line in lines:
        if line.strip() == "-----BEGIN CERTIFICATE-----":
            incert = True
        elif line.strip() == "-----END CERTIFICATE-----":
            incert = False
        elif incert:
            pem += line.strip()
        else:
            print >> sys.stderr, "Unexpected line"
    sys.stdout.write(base64.b64decode(pem))

pem2der(open(sys.argv[1], 'r') if len(sys.argv) > 1 else sys.stdin)
