name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: sudo apt-get install openssl gnutls-bin libnss3-tools
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - run: go get github.com/google/der-ascii/cmd/ascii2der
      - run: go get github.com/google/der-ascii/cmd/der2ascii
      - run: go get github.com/google/certificate-transparency-go/x509util/certcheck
      - name: Build gox509
        run: make bin/gox509
      - name: Run
        run: make
